export { Header } from './Header';
export { Hero } from './Hero';
export { Stats } from './Stats';
export { Features } from './Features';
export { HowItWorks } from './HowItWorks';
export { Categories } from './Categories';
export { Testimonials } from './Testimonials';
export { CTA } from './CTA';
export { Footer } from './Footer';
